#!/usr/bin/env bash
# Collect self-contained AppMap before/after comparison bundles produced by the
# review pipeline. The files are inert JSON and can be opened by the AppMap VS Code
# comparison editor without the original CI workspace.
set -euo pipefail

source_dir="${COMPARISON_SOURCE_DIR:-${TMPDIR:-/tmp}/appmap-review/out/report}"
output_dir="${COMPARISON_OUTPUT_DIR:-$(pwd)/.appmap/review/comparison}"
artifact_name="${COMPARISON_ARTIFACT_NAME:-appmap-behavior-comparison}"

rm -rf "$output_dir"
mkdir -p "$output_dir"

validate_bundle() { # <file>
  jq -e '
    .kind == "appmap.comparison" and
    .schemaVersion == 1 and
    (.producer.name | type == "string") and
    (.producer.version | type == "string") and
    (.scenario.id | type == "string") and
    (.recordings.base | type == "string") and
    (.recordings.head | type == "string") and
    .capabilities.views.sequence == 1 and
    (.views.sequence.base.actors | type == "array") and
    (.views.sequence.head.actors | type == "array") and
    (.views.sequence.diff.actors | type == "array") and
    (.views.sequence.alignment.actorOrder | type == "array") and
    (.changes | type == "array") and
    (all(.changes[]; .id | test("^chg_[0-9a-f]{20}(_[2-9][0-9]*|_[1-9][0-9]+)?$")))
  ' "$1" >/dev/null 2>&1
}

count=0
if [[ -d "$source_dir" ]]; then
  while IFS= read -r -d '' file; do
    if ! validate_bundle "$file"; then
      echo "::warning file=${file}::Skipping invalid or unsupported AppMap comparison bundle"
      continue
    fi

    relative="${file#"$source_dir"/}"
    destination="$output_dir/$relative"
    mkdir -p "$(dirname "$destination")"
    cp "$file" "$destination"
    count=$((count + 1))
  done < <(find "$source_dir" -type f -name '*.compare.diff.sequence.json' -print0)
fi

if [[ $count -eq 0 ]]; then
  rm -rf "$output_dir"
  echo "No valid interactive AppMap comparison bundles were produced."
  echo "available=false" >> "$GITHUB_OUTPUT"
  echo "path=" >> "$GITHUB_OUTPUT"
  echo "artifact-name=" >> "$GITHUB_OUTPUT"
  echo "footer-file=" >> "$GITHUB_OUTPUT"
  exit 0
fi

cat > "$output_dir/README.md" <<EOF
# AppMap behavioral comparison

This artifact contains ${count} self-contained before/after comparison bundle(s)
using the frozen \`appmap.comparison\` schema version 1.

1. Install a version of the AppMap VS Code extension with comparison support.
2. Open any \`*.compare.diff.sequence.json\` file.
3. Navigate the before and after diagrams side by side and use the unified diff below them.

The bundle data is sanitized AppMap-derived structure generated by CI. The JSON
contract is view-neutral even though Sequence Diagram is currently the first
implemented view.
EOF

footer_file="$(pwd)/.appmap/review/comparison-footer.md"
mkdir -p "$(dirname "$footer_file")"
cat > "$footer_file" <<EOF
### Interactive comparison

CI produced **${count}** portable before/after AppMap comparison bundle(s) using
\`appmap.comparison\` schema v1. Download the **\`${artifact_name}\`** workflow
artifact and open a \`*.compare.diff.sequence.json\` file with the AppMap VS Code
extension.
EOF

echo "Packaged ${count} interactive comparison bundle(s) in $output_dir."
echo "available=true" >> "$GITHUB_OUTPUT"
echo "path=$output_dir" >> "$GITHUB_OUTPUT"
echo "artifact-name=$artifact_name" >> "$GITHUB_OUTPUT"
echo "footer-file=$footer_file" >> "$GITHUB_OUTPUT"
